# Generated by Django 3.1.7 on 2022-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220308_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_feature',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
