# Generated by Django 3.1.7 on 2022-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_item_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_feature',
            field=models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2),
        ),
    ]
