# Generated by Django 3.1.7 on 2022-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220310_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='category_feature',
            field=models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2),
        ),
    ]
