# Generated by Django 3.1.7 on 2022-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_itemcategory_category_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('SA', 'Sale'), ('OUT', 'Out Of Stock')], default='SA', max_length=20),
        ),
    ]
